# Generated by Django 2.2.7 on 2019-11-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('email', models.CharField(blank=True, max_length=255)),
                ('about_me', models.TextField(blank=True)),
                ('preferred_classes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('tablename', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=255)),
                ('about_table', models.TextField()),
                ('game_type', models.CharField(max_length=255)),
                ('tablesize_pref', models.CharField(max_length=255)),
                ('homebrew', models.CharField(max_length=255)),
                ('alcohol', models.CharField(max_length=255)),
                ('session_lengths', models.CharField(max_length=255)),
                ('table_times', models.CharField(max_length=255)),
                ('table_status', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='app_DnD.Player')),
                ('players', models.ManyToManyField(through='app_DnD.Membership', to='app_DnD.Player')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_DnD.Player'),
        ),
        migrations.AddField(
            model_name='membership',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_DnD.Table'),
        ),
    ]
