# Generated by Django 2.2.7 on 2019-11-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DnD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
